### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Pukimaa** [an-object-is-a/reactjs-markdown-dynamic-file#1]
This is great...but I want a site (/blog) that automatically shows me all blogpost (Markdown Files in a folder) and if I click the "Read" Button it will take me to a new path (/blog/filename-of-markdown-file) which will also work dynamically so I don't need to touch the code ever again and just need to create new Markdown Files in the folder I specified in the code. How can I do that? I found no helpful ressource making it the exact I want.

**Comment by dylexBenjis** [comment]
I am building that same functionality in your question right now...I use react...and I wrote a function that respond to the clicked link post with the appropriate md file...

**Comment by dylexBenjis** [comment]
In react route I passed a variable to path...the variable contains the appropriate link post pointer

**Comment by Pukimaa** [comment]
Oh thanks for your answer. Actually I'm using completely different technologies now haha. Will close this now, since it was literal ages ago haha.
